Pass parmeter types to PQexecParams() explicitly, otherwise PostgreSQL will be guessing them based on field type and in the case of mismatch may bail with cryptic error message:
"ERROR: dbase.c:783: Error: ERROR:  insufficient data left in message"

Particularly, this happens easily with integers - SER is packing 4 bytes,
while PG expects 8 bytes.

Sponsored by:	Sippy Software, Inc. ( http://www.sippysoft.com/ )